version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bbip_app
    restart: unless-stopped
    working_dir: /app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    volumes:
      - ./:/app:delegated
      - /app/vendor
      - /app/node_modules
    ports:
      - "8001:8000"
    command: php artisan serve --host=0.0.0.0

  vite:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: bbip_vite
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    ports:
      - "5180:5173"
    environment:
      - VITE_HOST=localhost
    command: npm run dev
